clusterName: kube-cluster
talosVersion: v1.1.2
kubernetesVersion: v1.24.3
endpoint: https://${clusterEndpointIP}:6443
allowSchedulingOnMasters: true
clusterPodNets:
  - 10.200.0.0/16
clusterSvcNets:
  - 10.210.0.0/12
cniConfig:
  name: none
nodes:
  - hostname: kube-cp-01
    ipAddress: 10.1.10.21
    controlPlane: true
    installDisk: /dev/sda
    networkInterfaces:
      - interface: eth0
        mtu: 1500
        dhcp: true
        vip:
          ip: ${clusterEndpointIP}
#  - hostname: kube-cp-02
#    ipAddress: 10.1.10.22
#    controlPlane: true
#    installDisk: /dev/sda
#    networkInterfaces:
#      - interface: eth0
#        mtu: 1500
#        dhcp: true
#  - hostname: kube-cp-03
#    ipAddress: 10.1.10.23
#    controlPlane: true
#    installDisk: /dev/sda
#    networkInterfaces:
#      - interface: eth0
#        mtu: 1500
#        dhcp: true

controlPlane:
  configPatches:
    - op: add
      path: /machine/kubelet/extraArgs
      value:
        feature-gates: GracefulNodeShutdown=true,EphemeralContainers=true,ServerSideApply=true
        rotate-server-certificates: "true"
  inlinePatch:
    cluster:
      aescbcEncryptionSecret: ${aescbcEncryptionKey}
      aggregatorCA:
        crt: ${k8sAggregatorCert}
        key: ${k8sAggregatorCertKey}
      apiServer:
        admissionControl: []
        certSANs:
          - kube-cluster
          - kube-cluster.${domainName}
      ca:
        crt: ${clusterCert}
        key: ${clusterCertKey}
      controllerManager:
        extraArgs:
          bind-address: 0.0.0.0
      discovery:
        registries:
          service:
            disabled: true
      etcd:
        ca:
          crt: ${etcdCert}
          key: ${etcdCertKey}
      extraManifests:
        - https://raw.githubusercontent.com/alex1989hu/kubelet-serving-cert-approver/main/deploy/standalone-install.yaml
      proxy:
        disabled: true
      scheduler:
        extraArgs:
          bind-address: 0.0.0.0
      secret: ${clusterSecret}
      serviceAccount:
        key: ${k8sServiceAccountKey}
      token: ${clusterToken}
    machine:
      ca:
        crt: ${machineCert}
        key: ${machineCertKey}
      certSANs:
        - kube-cluster
        - kube-cluster.${domainName}
      files:
        - content: |
            [plugins."io.containerd.grpc.v1.cri"]
              enable_unprivileged_ports = true
              enable_unprivileged_icmp = true
          path: /var/cri/conf.d/allow-unpriv-ports.toml
          op: create
      install:
        extraKernelArgs:
          - talos.logging.kernel=udp://10.45.0.2:6050/
          - nvme_core.default_ps_max_latency_us=5500
          - pci=noaer
      logging:
        destinations:
          - endpoint: udp://10.1.10.49:6051/
            format: json_lines
      network:
        extraHostEntries:
          - ip: 10.1.10.10
            aliases:
              - apollo
              - apollo.${domainName}
      time:
        servers:
          - 10.1.10.5
          - time.cloudflare.com
      token: ${machineToken}
      udev:
        rules:
          - SUBSYSTEM=="drm", KERNEL=="card*", GROUP="44", MODE="0660"
          - SUBSYSTEM=="drm", KERNEL=="renderD*", GROUP="44", MODE="0660"

worker:
  configPatches:
    - op: add
      path: /machine/kubelet/extraArgs
      value:
        feature-gates: GracefulNodeShutdown=true,EphemeralContainers=true,ServerSideApply=true
        rotate-server-certificates: "true"
  inlinePatch:
    cluster:
      aescbcEncryptionSecret: ${aescbcEncryptionKey}
      ca:
        crt: ${clusterCert}
        key: ${clusterCertKey}
      secret: ${clusterSecret}
      token: ${clusterToken}
    machine:
      ca:
        crt: ${machineCert}
        key: ${machineCertKey}
      certSANs:
        - kube-cluster
        - kube-cluster.${domainName}
      files:
        - content: |
            [plugins."io.containerd.grpc.v1.cri"]
              enable_unprivileged_ports = true
              enable_unprivileged_icmp = true
          path: /var/cri/conf.d/allow-unpriv-ports.toml
          op: create
      install:
        extraKernelArgs:
          - talos.logging.kernel=udp://10.45.0.2:6050/
          - nvme_core.default_ps_max_latency_us=5500
          - pci=noaer
      logging:
        destinations:
          - endpoint: udp://10.1.10.49:6051/
            format: json_lines
      network:
        extraHostEntries:
          - ip: 10.1.10.10
            aliases:
              - apollo
              - apollo.${domainName}
      time:
        servers:
          - 10.1.10.5
          - time.cloudflare.com
      token: ${machineToken}
      udev:
        rules:
          - SUBSYSTEM=="drm", KERNEL=="card*", GROUP="44", MODE="0660"
          - SUBSYSTEM=="drm", KERNEL=="renderD*", GROUP="44", MODE="0660"
