---
kubeProxyReplacement: "strict"
ipv4NativeRoutingCIDR: 10.200.0.0/16
k8sServiceHost: 10.1.10.20
k8sServicePort: 6443
tunnel: "disabled"
autoDirectNodeRoutes: true
ipam:
  mode: "kubernetes"
operator:
  replicas: 1
securityContext:
  privileged: true
hubble:
  enabled: false
bgp:
  enabled: false
  announce:
    loadbalancerIP: true
