---
collections:
  - name: ansible.posix
    version: 2.0.0
  - name: ansible.utils
    version: 6.0.0
  - name: community.general
    version: 10.6.0
  - name: community.sops
    version: 2.0.5
  - name: community.docker
    version: 4.5.2
  - name: kubernetes.core
    version: 5.2.0
roles:
  - name: geerlingguy.pip
    version: 3.1.0
  - name: mrlesmithjr.zfs
    scm: git
    src: https://github.com/mrlesmithjr/ansible-zfs.git
    version: 9560a44eb013bbfd0705f57651c0174638e81e3f
  - name: geerlingguy.docker
    version: 7.4.7
  - name: bodsch.snapd
    version: 1.4.0
  - name: xanmanning.k3s
    version: v3.4.4
