directories:
  downloads: /media/.downloads/soulseek/complete
  incomplete: /media/.downloads/soulseek/incomplete
metrics:
  enabled: true
  url: /metrics
  authentication:
    disabled: true
permissions:
  file:
    mode: 664
shares:
  directories:
    - /media/soulseek
  filters:
    - \.ini$
    - Thumbs.db$
    - \.DS_Store$
web:
  authentication:
    api_keys:
      default:
        key: ${SLSKD_API_KEY}
        cidr: 0.0.0.0/0,::/0
