apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cilium-charts.yaml
  - node-feature-discovery-charts.yaml
  - prometheus-community-charts.yaml
  - bitnami-charts.yaml
  - metallb-charts.yaml
  - ingress-nginx-charts.yaml
  - jetstack-charts.yaml
  - k8s-at-home-charts.yaml
  - infracloudio-charts.yaml
  - grafana-charts.yaml
  - stakater-charts.yaml
  - lwolf-charts.yaml
  - emberstack-reflector-charts.yaml
  - metrics-server-charts.yaml
  - fairwinds-charts.yaml
  - xunholy-charts.yaml
  - aqua-charts.yaml
  - rook-ceph.yaml
  - kyverno-charts.yaml