---
apiVersion: v1
kind: Secret
metadata:
  name: radarr-restic-secret
  namespace: downloads
stringData:
  RESTIC_REPOSITORY: "${RESTIC_REPOSITORY}/radarr"
  RESTIC_PASSWORD: ${RESTIC_PASSWORD}
  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: radarr
  namespace: downloads
spec:
  sourcePVC: radarr-config
  trigger:
    schedule: "0 5 * * *"
  restic:
    cacheCapacity: 3G
    copyMethod: Snapshot
    pruneIntervalDays: 7
    repository: radarr-restic-secret
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    retain:
      daily: 7
      within: 3d
    volumeSnapshotClassName: zfs-alpha-snap
    storageClassName: rook-ceph-block
    cacheStorageClassName: local-hostpath
