---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: downloads
resources:
  - ./namespace.yaml
  - ./recyclarr/ks.yaml
  - ./prowlarr/ks.yaml
  - ./radarr/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./sonarr/ks.yaml
components:
  - ../../components/alerts
