---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./helm-release.yaml
configMapGenerator:
  - name: slskd-coredns
    files:
      - ./config/Corefile
  - name: slskd-configmap
    files:
      - slskd.yml=./config/slskd.yml
      - wrtag.sh=./scripts/wrtag.sh
generatorOptions:
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
  disableNameSuffixHash: true
configurations:
  - kustomizeconfig.yaml
