---
#
# SECRET* vars are encrypted with sops
#

os_timezone: "Europe/London"
os_ssh_authorized_keys:
  - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJnp4n7WX1FgQozEi6qY+E/6y3yg6eqnAdpQHp1MkMTH paul@LAPTOP"
os_packages_repositories:
  - ppa:neovim-ppa/unstable
os_packages_install:
  - apt-transport-https
  - aardvark-dns
  - ca-certificates
  - curl
  - gettext
  - git
  - htop
  - netavark
  - neofetch
  - neovim
  - ntpdate
  - podman
  - podman-plugins
  - psmisc
  - samba
  - software-properties-common
  - tmux
  - uidmap
  - unzip
  - wsdd2
  - zfs-zed
  - zfsutils-linux
os_packages_remove:
  - apparmor
  - apport
  - byobu
  - friendly-recovery
  - landscape-common
  - lxd-agent-loader
  - plymouth
  - plymouth-theme-ubuntu-text
  - popularity-contest
  - snapd
  - sosreport
  - ubuntu-advantage-tools
  - ufw
