---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
  - namespace.yaml
  - alertmanager-discord
  - kube-prometheus
  - grafana
#  - loki
#  - vector
#  - generic-rules
#  - botkube
