---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: music-assistant
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      music-assistant:
        pod:
          annotations:
            k8s.v1.cni.cncf.io/networks: |
              [{
                "name":"multus-iot",
                "namespace": "networking",
                "ips": [
                  "10.1.20.38/24",
                  "fd79:4c9c:b9c3:20::38/64"
                ]
              }]
          securityContext:
            runAsNonRoot: true
            runAsUser: 2000
            runAsGroup: 2000
            fsGroup: 2000
            fsGroupChangePolicy: OnRootMismatch
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/music-assistant/server
              tag: 2.7.2@sha256:8fc7f780a0a30594e170d5a71138852b1a1e7ce33d2d460e50bf8cadf9eda74f
            env:
              TZ: Europe/London
              LOG_LEVEL: info
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
                add:
                  - SYS_ADMIN
                  - DAC_READ_SEARCH
          alexa-api:
            image:
              repository: ghcr.io/alams154/music-assistant-skill
              tag: dev@sha256:68c29a37828d729c45c0c8244c0226a79c4a9d08811dd845bdeef38ee416fc23
            env:
              TZ: Europe/London
              MA_HOSTNAME: mass-st.starsreak.net
              PORT: 5000
              DEBUG_PORT: 5678
              AWS_DEFAULT_REGION: us-east-1
            envFrom:
              - secretRef:
                  name: mass-alexa-api-secret
    service:
      app:
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: 10.1.10.38
        ports:
          http:
            port: &port 8095
            primary: true
          stream:
            port: 8097
          connect:
            port: 32500
          gdm1:
            port: 32410
            protocol: UDP
          gdm2:
            port: 32412
            protocol: UDP
          gdm3:
            port: 32413
            protocol: UDP
          gdm4:
            protocol: UDP
            port: 32414
      alexa-api:
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: 10.1.10.39
        ports:
          alexa-api:
            port: &alexa-api-port 5000
          alexa-api-debug:
            port: 5678
    route:
      app:
        annotations:
          gatus.home-operations.com/endpoint: |-
            conditions: ["[STATUS] == 200"]
        hostnames:
          - mass.starstreak.net
        parentRefs:
          - name: envoy-internal
            namespace: networking
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
      app-st:
        hostnames:
          - mass-st.starstreak.net
        parentRefs:
          - name: envoy-external
            namespace: networking
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: 8079
      alexa-api:
        hostnames:
          - mass-alexa-api.starstreak.net
        parentRefs:
          - name: envoy-external
            namespace: networking
            sectionName: https
        rules:
          - backendRefs:
              - identifier: alexa-api
                port: *alexa-api-port
    persistence:
      data:
        existingClaim: music-assistant-config
        advancedMounts:
          music-assistant:
            app:
              - path: /data
                subPath: data
              - path: /cache
                subPath: cache
              - path: /.local
                subPath: .local
      tmp:
        type: emptyDir
