---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-recyclarr
  namespace: flux-system
spec:
  interval: 10m
  path: "./clusters/compute/k8s/apps/downloads/recyclarr/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  wait: false # no flux ks dependents
  dependsOn:
    - name: cluster-apps-democratic-csi-zfs-local-dataset
