---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: media
resources:
  - ./namespace.yaml
  - ./music-assistant/ks.yaml
  - ./plex/ks.yaml
  - ./tautulli/ks.yaml
  - ./tvheadend/ks.yaml
components:
  - ../../components/alerts
