---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - ./namespace.yaml
  - ./cilium/ks.yaml
  - ./coredns/ks.yaml
  - ./gateway-api-crds/ks.yaml
  - ./metrics-server/ks.yaml
  - ./snapshot-controller/ks.yaml
components:
  - ../../components/alerts
