---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: ignition
resources:
  - ./namespace.yaml
  #  - ./database/ks.yaml
  - ./backend/ks.yaml
  #  - ./frontend/ks.yaml
components:
  - ../../components/alerts
