---
collections:
  - name: ansible.posix
    version: 2.1.0
  - name: ansible.utils
    version: 6.0.1
  - name: community.general
    version: 12.3.0
  - name: community.docker
    version: 5.0.5
roles:
  - name: geerlingguy.pip
    version: 3.1.2
  - name: mrlesmithjr.zfs
    scm: git
    src: https://github.com/mrlesmithjr/ansible-zfs.git
    version: 9560a44eb013bbfd0705f57651c0174638e81e3f
  - name: geerlingguy.docker
    version: 8.0.0
  - name: bodsch.snapd
    version: 1.4.0
