---
# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
clusterName: darkstar
endpoint: https://darkstar.lan.starstreak.net:6443

# renovate: datasource=docker depName=ghcr.io/siderolabs/installer
talosVersion: v1.11.5
# renovate: datasource=docker depName=ghcr.io/siderolabs/kubelet
kubernetesVersion: v1.34.2

allowSchedulingOnMasters: true

additionalApiServerCertSans: &san
  - darkstar.lan.starstreak.net
  - 127.0.0.1
additionalMachineCertSans: *san

clusterPodNets:
  - 10.244.0.0/16
  - fd79:4c9c:b9c3:2400::/56
clusterSvcNets:
  - 10.96.0.0/12
  - fd79:4c9c:b9c3:9600::/112

cniConfig:
  name: none

nodes:
  - hostname: alpha.lan.starstreak.net
    ipAddress: 10.1.10.21
    controlPlane: true
    disableSearchDomain: true
    installDiskSelector:
      model: INTEL *
    kernelModules:
      - name: dm_thin_pool
      - name: dm_mod
    machineSpec:
      secureboot: true
      useUKI: true
    nameservers:
      - 10.1.10.1
    networkInterfaces:
      - deviceSelector:
          driver: e1000e
          hardwareAddr: "*:70:e2"
        mtu: 1500
        dhcp: true
        vip:
          ip: 10.1.10.20
        vlans:
          - vlanId: 20
            mtu: 1500
            dhcp: false
          - vlanId: 30
            mtu: 1500
            dhcp: false
          - vlanId: 50
            mtu: 1500
            dhcp: false
    nodeLabels:
      intel.feature.node.kubernetes.io/gpu: "true"
    userVolumes:
      - name: usb
        provisioning:
          diskSelector:
            match: disk.transport == "usb"
          maxSize: 1TB
        filesystem:
          type: xfs

controlPlane:
  schematic:
    customization:
      extraKernelArgs:
        - net.ifnames=1 # Enable predictable NIC naming
        - nvme_core.default_ps_max_latency_us=5500
        - pci=noaer
        - -selinux
      systemExtensions:
        officialExtensions:
          - siderolabs/i915
          - siderolabs/intel-ucode
          - siderolabs/mei
          - siderolabs/nfsrahead
  patches:
    # Configure cluster
    - |-
      cluster:
        apiServer:
          admissionControl:
            $$patch: delete
          extraArgs:
            enable-aggregator-routing: true
            runtime-config: admissionregistration.k8s.io/v1beta1=true
            feature-gates: MutatingAdmissionPolicy=true,ResourceHealthStatus=true
        controllerManager:
          extraArgs:
            bind-address: 0.0.0.0
        coreDNS:
            disabled: true
        proxy:
          disabled: true
        scheduler:
          extraArgs:
            bind-address: 0.0.0.0

    - |-
      machine:
        features:
          kubernetesTalosAPIAccess:
            enabled: true
            allowedRoles:
              - os:admin
            allowedKubernetesNamespaces:
              - system-upgrade
              - actions-runner-system
          hostDNS:
            enabled: true
            resolveMemberNames: true
            forwardKubeDNSToHost: false
        files:
          - op: create
            path: /etc/cri/conf.d/20-customization.part
            content: |
              [plugins."io.containerd.cri.v1.images"]
                discard_unpacked_layers = false
              [plugins."io.containerd.cri.v1.runtime"]
                cdi_spec_dirs = ["/var/cdi/static", "/var/cdi/dynamic"]
                device_ownership_from_security_context = true
          - op: overwrite
            path: /etc/nfsmount.conf
            permissions: 0o644
            content: |
              [ NFSMount_Global_Options ]
              nfsvers=4.2
              hard=True
              noatime=True
              nodiratime=True
              rsize=131072
              wsize=131072
              nconnect=8
        kubelet:
          extraConfig:
            featureGates:
              ImageVolume: true
              ResourceHealthStatus: true            
            maxPods: 250
          extraMounts:
            - destination: /var/mnt/openebs/local
              type: bind
              source: /var/mnt/openebs/local
              options:
                - bind
                - rshared
                - rw
          nodeIP:
            validSubnets:
              - 10.1.10.0/24
              - fd79:4c9c:b9c3:10::/108
        network:
          extraHostEntries:
            - ip: 10.1.10.1
              aliases:
                - gw
                - gw.lan.starstreak.net
            - ip: 10.1.10.10
              aliases:
                - apollo
                - apollo.lan.starstreak.net
            - ip: 10.1.10.20
              aliases:
                - darkstar
                - darkstar.lan.starstreak.net
        time:
          disabled: false
          servers:
            - 10.1.10.1
