---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ignition
spec:
  interval: 1h
  chart:
    spec:
      chart: ignition
      version: 0.2.1
      sourceRef:
        kind: HelmRepository
        name: ia-charts
        namespace: flux-system
      interval: 1h
  values:
    certManager:
      enabled: true
    commissioning:
      acceptIgnitionEULA: true
      auth:
        adminUsername: localadmin
        adminPasswordKey: gateway-admin-password
        existingSecret: ignition-gateway-secret
      edition: "maker"
    gateway:
      dataVolumeStorageClass: topolvm-thin-provisioner
      dataVolumeStorageSize: 5Gi
      env:
        - name: EAM_SETUP_INSTALLSELECTION
          value: "Controller"
      licensing:
        leasedActivation:
          activationTokenKey: ignition-activation-token
          licenseKeyKey: ignition-license-key
          secretName: ignition-gateway-secret
      tls:
        enabled: true
    ingress:
      enabled: false
    podAnnotations:
      reloader.stakater.com/auto: "true"
