---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ignition
spec:
  interval: 1h
  chart:
    spec:
      chart: ignition
      version: 0.2.0
      sourceRef:
        kind: HelmRepository
        name: ia-charts
        namespace: flux-system
      interval: 1h
  values:
    certManager:
      enabled: true
    gateway:
      dataVolumeStorageClass: topolvm-thin-provisioner
      dataVolumeStorageSize: 5Gi
      env:
        - name: EAM_SETUP_INSTALLSELECTION
          value: "Controller"
      envFrom:
        - secretRef:
            name: gateway-base-secret
      tls:
        enabled: true
    ingress:
      enabled: false
    podAnnotations:
      reloader.stakater.com/auto: "true"
