# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: home-assistant
stringData:
    HASS_LATITUDE: ENC[AES256_GCM,data:w+cfikqfuS3/,iv:+5KXS8QS//Y9Bl22k1/GAr8OqrjgkhYQSwRnQ27Bp60=,tag:4wOzNammx8zGpiZnJvNsGg==,type:str]
    HASS_LONGITUDE: ENC[AES256_GCM,data:zTVeUV3MOy9F,iv:6h7aWnnbUMDw9ThIMQj3yfy47aCGciTttdAOsgbb9PA=,tag:RjjbOAPNk2FkmaHwuYj7mA==,type:str]
    HASS_ELEVATION: ENC[AES256_GCM,data:XjY=,iv:BCXlUzPlpIVWBCw91H7EBaDDBTNvAR2YMNodyAQXRXw=,tag:XRLrbLoTMWowrE8RDQOABA==,type:str]
    #ENC[AES256_GCM,data:++N20d2eTvtwnEzGzF8DcC3VjHYjXj+dbozAL4Gvy7/NQBQhwaiENi4XDFlVZ0nb4giGnJWmoVYyh1Vn,iv:WOPiHd5jm7GL4FaMdiDFhUB5Irl+fNZj4eE5WBy55lA=,tag:KQD/ZXqT0u/6CUhDUPnqmA==,type:comment]
    HASS_TRUSTED_PROXIES: ENC[AES256_GCM,data:UGITi0vABy1o0eJ2Fg==,iv:+sWgNxYxQU1R/i4fUh8qfz7zQ4AJIEWwXlX3pTd3be8=,tag:i1jI/X1CfQCyb7P7jKGVRA==,type:str]
    #ENC[AES256_GCM,data:AHpONzl9Xj60qGbQtQ==,iv:sLaL6M819D083wXatZNPiPUxrDT/THyfQUdQcXRJuas=,tag:MJmecjrwBGX3j1Tnb8UTlQ==,type:comment]
    HASS_HIVE_USERNAME: ENC[AES256_GCM,data:E7Mf1Xydinri9X6gXUGCZrIOBw==,iv:EueE68nwSmscPmfPTLSgFaPa7894/Q4Gp+B57CNkpk4=,tag:PSsXMW5vyeg7+opJjAoeHg==,type:str]
    HASS_HIVE_PASSWORD: ENC[AES256_GCM,data:aTuAzWtNW+p2Gn6W6Lk=,iv:6JOi0CXsPWWe6ejFmx1tdtHnIpV7t6lvUjvdfHnq8Nk=,tag:KvL3572fC31b1T8MAAhebg==,type:str]
    HASS_LG_OLED_MAC: ENC[AES256_GCM,data:We7xhfni5EAHeoEGs8fozXI=,iv:i8cwS9NCbC+OncZ7ZgbXuHeGIgQTg44qFtqjBMa1rM8=,tag:D/0h2ATvuEOE2JrijSOpbg==,type:str]
    HASS_ALEXA_CLIENT_ID: ENC[AES256_GCM,data:M5gUFlEzC6Z45KedKIizmi9L1KSyBSF7tQ47Xpr7fUOtjSLteAxirDSJWPCSasQoS8DzaAlAKbUZ0iXC2g==,iv:5PzIbr2YeGqoPBzUJzkdMEsB7AtI1nK3xJj4gfqZkx4=,tag:8HcMyuJo5I+6NXt0XH0J3w==,type:str]
    HASS_ALEXA_CLIENT_SECRET: ENC[AES256_GCM,data:pcqYjw665BDEKDjfPs7SiY+noPFoEnNHzpI62ecjLMtj806Vs/OUJ/cJkh6to77aWRDS2w8GJUxpPQ+KgnGlLw==,iv:o2O1lx5HE39RcdI+IdlrE20ZyfBTqcdAO9dRJ/MGqsA=,tag:ztq86xMPBa8iUY188tQLzw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kpfj2296mrlq75ffktg9zksgausntzamd7tu88hcxm2mytray3aqqp33yr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPRFQ1cFdvQjhVQlN6NWFL
            NFpod0ZYcGZNYTJQZHFSM2Y2bzY5bVBVNWtnCnRadXNWb2k4NTU1V2JJSlQ1MHZz
            ekRsUGxEU0FhbnJ2L3FoVWt0Z3BXWmcKLS0tIGlxRkVuc2U1RUVFVlhnci9EUzhk
            VTBHU3lCelVacXVMZUhKRTZrMzRMaEUKSwmSxZKmEOQ1f1Dn2GqWiXvDk9Cpeylh
            Uy76+MydfCbTtEbvejeybeuuxWnoKB06VuXWRSj1XzH8ZRb43Owi/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-12T23:54:37Z"
    mac: ENC[AES256_GCM,data:t3bJ39EWoeaSa8h0A12DKj9CVkRktb0eVCcvY5v6ZtlP92I6aSROfhi2h70Sz0JNkrihAJxWCm275mp/iIWkscyZyzGJmq4QGlxnxfe7Dh8k7WErbFgHXXc0ZW/LwbfFv7+Y2+NrnWQLTiXx4JooMG1HPLNQkdTrVs1oWIwsVtE=,iv:KqEF/Pp0aniXSoLSTZ87GrGJ3wtRFlhpHUNiQA14q1w=,tag:2wDxiAZEZ3fFaA148YLdew==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
