---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
  - ./namespace.yaml
  - ./common/ks.yaml
  - ./windows/ks.yaml
