---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TZ: Europe/London
  CLUSTER_NAME: darkstar
  SVC_LB_INGRESS_NGINX_INT: 10.1.10.30
  SVC_LB_INGRESS_NGINX_EXT: 10.1.10.31
  SVC_LB_PLEX: 10.1.10.32
  SVC_LB_HASS: 10.1.10.33
  SVB_LB_MOSQUITO: 10.1.10.34
  SVC_LB_MATTER: 10.1.10.35
  IP_ADDR_LAN_GW: 10.1.10.1
  IP_ADDR_LAN_NAS: 10.1.10.10
  IP_ADDR_LAN_GRAVITY: 10.1.10.98
  IP_ADDR_IOT_ZIGBEE: 10.1.20.101
