---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./alertmanagerconfig.yaml
  - ./helmrelease.yaml
  - ./scrapeconfigs
  - ./record
  - ./rules
