---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-vector-aggregator
  namespace: flux-system
spec:
  interval: 10m
  path: "./clusters/compute/k8s/apps/monitoring/vector/aggregator"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  wait: false # no flux ks dependents
  dependsOn:
    - name: cluster-apps-k8s-ycl
    - name: cluster-apps-k8tz
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-vector-agent
  namespace: flux-system
spec:
  interval: 10m
  path: "./clusters/compute/k8s/apps/monitoring/vector/agent"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  wait: false # no flux ks dependents
  dependsOn:
    - name: cluster-apps-vector-aggregator
    - name: cluster-apps-k8s-ycl
    - name: cluster-apps-k8tz
