---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./backube-charts.yaml
  - ./enix-charts.yaml
  - ./ia-charts.yaml
  - ./intel-charts.yaml
  - ./k8tz-charts.yaml
  - ./keda-charts.yaml
  - ./kubernetes-sigs-external-dns-charts.yaml
  - ./metrics-server-charts.yaml
  - ./postfinance-charts.yaml
  - ./topolvm-charts.yaml
