---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname tuppr
  namespace: &namespace system-upgrade
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: tuppr
      namespace: system-upgrade
  interval: 1h
  path: "./kubernetes/darkstar/apps/system-upgrade/tuppr/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
    namespace: flux-system
  wait: true
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname tuppr-upgrades
  namespace: &namespace system-upgrade
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 1h
  path: "./kubernetes/darkstar/apps/system-upgrade/tuppr/upgrades"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
    namespace: flux-system
  wait: false
  dependsOn:
    - name: tuppr
      namespace: system-upgrade
