---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-kvm-kubevirt
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/disabled: "true"
spec:
  interval: 5m
  prune: true
  wait: true
  path: "./deploy"
  sourceRef:
    kind: GitRepository
    name: kubevirt
  dependsOn: []
  patches:
    # namespace is managed separately by main ks, no need for this ks to also manage it, KubeVirt bundles namespace into kubevirt-operator.yaml
    - patch: |
        $patch: delete
        apiVersion: v1
        kind: Namespace
        metadata:
          name: kubevirt
      target:
        kind: Namespace
        name: kubevirt
    - patch: |
        apiVersion: kubevirt.io/v1
        kind: KubeVirt
        metadata:
          name: not-used
        spec:
          configuration:
            vmStateStorageClass: zfs-local-dataset
            developerConfiguration:
              featureGates:
                - VMPersistentState
                - AutoResourceLimitsGate
      target:
        group: kubevirt.io
        kind: KubeVirt
