---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: starstreak-net
spec:
  secretName: "starstreak-net-tls"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "starstreak.net"
    - "*.starstreak.net"
  duration: 160h
  usages:
    - "digital signature"
