auth:
  enabled: false

mqtt:
  host: mosquitto.database.svc.cluster.local
  port: 1883
  topic_prefix: frigate

database:
  path: /data/frigate.db

detectors:
  ov_0:
    type: openvino
    device: GPU

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

objects:
  track:
    - bicycle
    - car
    - cat
    - dog
    - fox
    - motorcycle
    - person
  filters:
    bicycle:
      threshold: 0.7
      min_score: 0.65
    car:
      threshold: 0.7
      min_score: 0.65
    cat:
      threshold: 0.6
      min_score: 0.5
    dog:
      threshold: 0.6
      min_score: 0.5
    fox:
      threshold: 0.7
      min_score: 0.5
    motorcycle:
      threshold: 0.7
      min_score: 0.65

ffmpeg:
  global_args:
    - -hide_banner
    - -loglevel
    - warning
    - -an
  hwaccel_args: preset-intel-qsv-h264

snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  retain:
    default: 7
  required_zones:
    - forecourt

record:
  enabled: true
  continuous:
    days: 3
  motion:
    days: 7
  alerts:
    retain:
      days: 14
      mode: all
  detections:
    retain:
      days: 30
      mode: all

go2rtc:
  streams:
    front:
      - rtsp://{FRIGATE_CAM_USER}:{FRIGATE_CAM_PASSWORD}@10.1.50.100:554/cam/realmonitor?channel=1&subtype=0
    front_sub:
      - rtsp://{FRIGATE_CAM_USER}:{FRIGATE_CAM_PASSWORD}@10.1.50.100:554/cam/realmonitor?channel=1&subtype=1

cameras:
  front:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      filters:
        car:
          mask:
            - 0,0.858,0.271,0.331,0.238,0.214,0.175,0.151,0.06,0.192,0,0.242
    review:
      alerts:
        required_zones:
          - forecourt
      detections:
        required_zones:
          - forecourt
    zones:
      forecourt:
        coordinates: 0.362,0.290,0.11,1,1,1,0.751,0.290
        loitering_time: 2
        objects:
          - bicycle
          - car
          - cat
          - dog
          - fox
          - motorcycle
          - person
    motion:
      mask:
        - 0.978,0.03,0.978,0.081,0.725,0.081,0.725,0.03
    detect:
      enabled: true
      width: 704
      height: 480

tls:
  enabled: false
