---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
  - ./prowlarr-secret.sops.yaml
  - ./helm-release.yaml
  # PVC and volsync templates
  - ../../../storage/volsync/templates
  - ../../../monitoring/gatus/templates/internal
