---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: system
resources:
  - ./namespace.yaml
  - ./fstrim/ks.yaml
  - ./generic-device-plugin/ks.yaml
  - ./intel-gpu-resource-driver/ks.yaml
  - ./keda/ks.yaml
  - ./reloader/ks.yaml
components:
  - ../../components/alerts
