---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-grafana
  namespace: flux-system
spec:
  interval: 10m
  path: "./clusters/compute/k8s/apps/monitoring/grafana/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  wait: false # no flux ks dependents
  dependsOn:
    - name: cluster-apps-democratic-csi-zfs-local-dataset
    - name: cluster-apps-kube-prometheus-stack
    - name: cluster-apps-k8s-ycl
    - name: cluster-apps-k8tz
