---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
  - ./namespace.yaml
  - ./kube-prometheus-stack/ks.yaml
  - ./alertmanager/ks.yaml
  - ./node-exporter/ks.yaml
  - ./loki/ks.yaml
  - ./vector/ks.yaml
  - ./grafana/ks.yaml
