---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-democratic-csi-local-path
  namespace: flux-system
spec:
  path: "./clusters/compute/k8s/apps/system/democratic-csi/local-path"
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  interval: 10m
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-democratic-csi-zfs-local-dataset
  namespace: flux-system
spec:
  path: "./clusters/compute/k8s/apps/system/democratic-csi/zfs-local-dataset"
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  interval: 10m
  prune: true
  wait: true
